/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InventoryAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.OrderInventory.OrderInventory;
import Business.Organization.InventoryAdminOrganization;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InventoryAdminWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elena
 */
public class InventoryAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private InventoryAdminOrganization organization;
    private HospitalEnterprise hospitalEnterprise;
    //private SupplierEnterprise supplierEnterprise;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    //private SupplierDirectory supplierDir;
    //private OrderInventory oi;
    public InventoryAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InventoryAdminOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        //this.supplierDir=supplierDir;
        //this.oi=oi;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        //this.enterprise = enterprise;
        this.hospitalEnterprise=(HospitalEnterprise)enterprise;
        this.userAccount = account;
        this.business=business;
        hospitalEnterpriseTxt.setText(hospitalEnterprise.getName());
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            if(request instanceof InventoryAdminWorkRequest)
            {
               Object[] row = new Object[5];
            //row[3] = request;
            row[0] = request.getSender().getPerson().getName();
            //row[1] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
            row[1] = request.getStatus();
            row[2]= request.getMessage();
            
            model.addRow(row); 
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderInventoryBtn = new javax.swing.JButton();
        vaccinationCatalogBtn = new javax.swing.JButton();
        hospitalEnterpriseTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        orderInventoryBtn.setText("Check Order Inventory");
        orderInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderInventoryBtnActionPerformed(evt);
            }
        });

        vaccinationCatalogBtn.setText("Browse vaccination catalog");
        vaccinationCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinationCatalogBtnActionPerformed(evt);
            }
        });

        hospitalEnterpriseTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sender", "Status", "Vaccination Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vaccinationCatalogBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addComponent(orderInventoryBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(hospitalEnterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(hospitalEnterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(orderInventoryBtn)
                .addGap(53, 53, 53)
                .addComponent(vaccinationCatalogBtn)
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderInventoryBtnActionPerformed
        OrderItemJPanel bvc = new OrderItemJPanel(userProcessContainer,hospitalEnterprise.getOrderInventory());
        userProcessContainer.add("OrderItemJPanel", bvc);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);       // TODO add your handling code here:
    }//GEN-LAST:event_orderInventoryBtnActionPerformed

    private void vaccinationCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinationCatalogBtnActionPerformed
        BrowseVaccinationCatalog bvc = new BrowseVaccinationCatalog(userProcessContainer,userAccount,hospitalEnterprise.getOrderInventory(),organization,business,hospitalEnterprise);
        userProcessContainer.add("BrowseVaccinationCatalog", bvc);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinationCatalogBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hospitalEnterpriseTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderInventoryBtn;
    private javax.swing.JButton vaccinationCatalogBtn;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
