/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InventoryAdminRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.OrderInventory.OrderInventory;
import Business.Vaccination.Vaccination;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author Elena
 */
public class OrderItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderItemJPanel
     */
    private JPanel upc;
    //private SupplierDirectory supplierDir;
    private OrderInventory oi;
    public OrderItemJPanel(JPanel upc, OrderInventory oi) {
        initComponents();
        this.upc = upc;
        //this.supplierDir = supplierDir;
        this.oi = oi;
        populateTable();
    }

    public void populateTable() {
        int rowCount = vaccinationOrderInventory.getRowCount();
        DefaultTableModel model = (DefaultTableModel)vaccinationOrderInventory.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Vaccination v : oi.getVaccinationList()) {
            Object row[] = new Object[4];
            
            row[0] = v.getVaccineID();
            row[1] = v;
            row[2] = v.getPrice();
            row[3] = v.getAvailability();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vaccinationOrderInventory = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        availabilityTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        vaccinationOrderInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccination Id", "Vaccination Name", "Price", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccinationOrderInventory);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hospital Order Inventory");

        jButton1.setText("Order Inventory Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter the maximum availability for the report:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(availabilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(backBtn)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availabilityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc); 
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
            //String x;
            //Enterprise.EnterpriseType reportType = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();
            String vacAvailibility;
            vacAvailibility=availabilityTxt.getText();
            String regex="\\d+";
            int vac;
            if (vacAvailibility.isEmpty()|| vacAvailibility.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter an availability","Warning",JOptionPane.WARNING_MESSAGE);

        }
            else if(!vacAvailibility.matches(regex))
            {
                JOptionPane.showMessageDialog(null,"Please enter a valid availability","Warning",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
               vac=Integer.parseInt(vacAvailibility);
            
            DefaultCategoryDataset dataArray = new DefaultCategoryDataset();
            dataArray = getValues(dataArray,vac);
            JFreeChart barChart = ChartFactory.createBarChart("Vaccinations with low availability", "Vaccination","Availibility", dataArray, PlotOrientation.VERTICAL, false , true, false);
            
            CategoryPlot plot = barChart.getCategoryPlot();
            
            plot.setRangeGridlinePaint(Color.black);
            
            ChartFrame frame = new ChartFrame("Bar Chart for vaccinations with availability less than "+vacAvailibility,barChart);
            frame.setSize(450,350);
            frame.setVisible(true);
            
            }
            

            // TODO add your handling code here:
    }                                        

     public DefaultCategoryDataset getValues(DefaultCategoryDataset dataArray,int vac)
            {
                 //int counter1 = 0;
                 //int counter2=0;
        for(Vaccination v : oi.getVaccinationList())
        {
            if(v.getAvailability()<=vac)
            {
            dataArray.setValue(v.getAvailability(),v.getName(),v.getName());
            }
        }
            
            //counter1=0;
           /* if(enterpriseTypeJComboBox.getSelectedItem()=="Supplier")
            {
            dataArray.setValue(counter1,network.getName(),network.getName());
            counter1=0;
            }*/
           
            /*dataArray.setValue(network.getEnterpriseDirectory().getEnterpriseList().size(), "Values", "HR"+counter);
            dataArray.setValue(network.getEnterpriseDirectory().getEnterpriseList().size(), "Values", "SBP"+counter);
            dataArray.setValue(network.getEnterpriseDirectory().getEnterpriseList().size(), "Values", "Wght"+counter);  */ 
        
        return dataArray;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availabilityTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable vaccinationOrderInventory;
    // End of variables declaration//GEN-END:variables
}
